/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import 'react-native-gesture-handler' //For react-navigation
import messaging from '@react-native-firebase/messaging';
import {Notifications} from 'react-native-notifications';


messaging().setBackgroundMessageHandler((remoteMessage) => {
    Notifications.postLocalNotification({
        title: "Local notification B",
        body: "This notification was generated by the app!",
        extra: "data"
    });
});

AppRegistry.registerComponent(appName, () => App);
