/**
 * @format
 */

import {AppRegistry} from 'react-native';
import App from './App';
import {name as appName} from './app.json';
import 'react-native-gesture-handler' //For react-navigation
import messaging from '@react-native-firebase/messaging';
import {Notifications} from 'react-native-notifications';

messaging().setBackgroundMessageHandler(async (remoteMessage) => {
    Notifications.postLocalNotification({
        title: "Local notification B",
        body: "This notification was generated by the app!",
        extra: "data"
    });

    //It's not in the docs, but apparently this handler should return a promise.
    //Otherwise you get a "cannot resolve .then of undefined" error
    return Promise.resolve() 
});

AppRegistry.registerComponent(appName, () => App);

