require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '12.0'

project 'emit',
        'Dev.Debug' => :debug,
        'Dev.Release' => :release, 
        'Prod.Debug' => :debug,
        'Prod.Release' => :release

target 'emit' do
  # Pods for emit
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '7.3.0'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'RNFS', :path => '../node_modules/react-native-fs'

  # Pods for react-native-permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"

  target 'emitTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!(configurations: ['Dev.Debug', 'Prod.Debug'])
  post_install do |installer|
    flipper_post_install(installer)
  end

end